service: pdf-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  timeout: 20
  stackTags:
    Project: 'pdf-service'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::pdf-service-bucket-241205/*

plugins:
  - serverless-offline

package:
  include:
    - node_modules/**
  exclude:
    - node_modules/@aws-sdk/**

functions:
  hello:
    handler: src/handlerNew.generatePDF
    memorySize: 2048
    events:
      - httpApi:
          path: /generate
          method: get

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pdf-service-bucket-241205
